
/**
 * 枚举类型颜色
 */
const COLOR = function(e){
  this.color = e;
  this.valueOf = function(){
    return this.color
  }
  this.toString = function(){
    return this.color
  }
}
COLOR.ALICEBLUE = new COLOR("#F0F8FF"); 
COLOR.ANTIQUEWHITE = new COLOR("#FAEBD7"); 
COLOR.AQUA = new COLOR("#00FFFF"); 
COLOR.AQUAMARINE = new COLOR("#7FFFD4"); 
COLOR.AZURE = new COLOR("#F0FFFF"); 
COLOR.BEIGE = new COLOR("#F5F5DC"); 
COLOR.BISQUE = new COLOR("#FFE4C4"); 
COLOR.BLACK = new COLOR("#000000"); 
COLOR.BLANCHEDALMOND = new COLOR("#FFEBCD"); 
COLOR.BLUE = new COLOR("#0000FF"); 
COLOR.BLUEVIOLET = new COLOR("#8A2BE2"); 
COLOR.BROWN = new COLOR("#A52A2A"); 
COLOR.BURLYWOOD = new COLOR("#DEB887"); 
COLOR.CADETBLUE = new COLOR("#5F9EA0"); 
COLOR.CHARTREUSE = new COLOR("#7FFF00"); 
COLOR.CHOCOLATE = new COLOR("#D2691E"); 
COLOR.CORAL = new COLOR("#FF7F50"); 
COLOR.CORNFLOWERBLUE = new COLOR("#6495ED"); 
COLOR.CORNSILK = new COLOR("#FFF8DC"); 
COLOR.CRIMSON = new COLOR("#DC143C"); 
COLOR.CYAN = new COLOR("#00FFFF"); 
COLOR.DARKBLUE = new COLOR("#00008B"); 
COLOR.DARKCYAN = new COLOR("#008B8B"); 
COLOR.DARKGOLDENROD = new COLOR("#B8860B"); 
COLOR.DARKGRAY = new COLOR("#A9A9A9"); 
COLOR.DARKGREEN = new COLOR("#006400"); 
COLOR.DARKKHAKI = new COLOR("#BDB76B"); 
COLOR.DARKMAGENTA = new COLOR("#8B008B"); 
COLOR.DARKOLIVEGREEN = new COLOR("#556B2F"); 
COLOR.DARKORANGE = new COLOR("#FF8C00"); 
COLOR.DARKORCHID = new COLOR("#9932CC"); 
COLOR.DARKRED = new COLOR("#8B0000"); 
COLOR.DARKSALMON = new COLOR("#E9967A"); 
COLOR.DARKSEAGREEN = new COLOR("#8FBC8F"); 
COLOR.DARKSLATEBLUE = new COLOR("#483D8B"); 
COLOR.DARKSLATEGRAY = new COLOR("#2F4F4F"); 
COLOR.DARKTURQUOISE = new COLOR("#00CED1"); 
COLOR.DARKVIOLET = new COLOR("#9400D3"); 
COLOR.DEEPPINK = new COLOR("#FF1493"); 
COLOR.DEEPSKYBLUE = new COLOR("#00BFFF"); 
COLOR.DIMGRAY = new COLOR("#696969"); 
COLOR.DODGERBLUE = new COLOR("#1E90FF"); 
COLOR.FELDSPAR = new COLOR("#D19275"); 
COLOR.FIREBRICK = new COLOR("#B22222"); 
COLOR.FLORALWHITE = new COLOR("#FFFAF0"); 
COLOR.FORESTGREEN = new COLOR("#228B22"); 
COLOR.FUCHSIA = new COLOR("#FF00FF"); 
COLOR.GAINSBORO = new COLOR("#DCDCDC"); 
COLOR.GHOSTWHITE = new COLOR("#F8F8FF"); 
COLOR.GOLD = new COLOR("#FFD700"); 
COLOR.GOLDENROD = new COLOR("#DAA520"); 
COLOR.GRAY = new COLOR("#808080"); 
COLOR.GREEN = new COLOR("#008000"); 
COLOR.GREENYELLOW = new COLOR("#ADFF2F"); 
COLOR.HONEYDEW = new COLOR("#F0FFF0"); 
COLOR.HOTPINK = new COLOR("#FF69B4"); 
COLOR.INDIANRED = new COLOR("#CD5C5C"); 
COLOR.INDIGO = new COLOR("#4B0082"); 
COLOR.IVORY = new COLOR("#FFFFF0"); 
COLOR.KHAKI = new COLOR("#F0E68C"); 
COLOR.LAVENDER = new COLOR("#E6E6FA"); 
COLOR.LAVENDERBLUSH = new COLOR("#FFF0F5"); 
COLOR.LAWNGREEN = new COLOR("#7CFC00"); 
COLOR.LEMONCHIFFON = new COLOR("#FFFACD"); 
COLOR.LIGHTBLUE = new COLOR("#ADD8E6"); 
COLOR.LIGHTCORAL = new COLOR("#F08080"); 
COLOR.LIGHTCYAN = new COLOR("#E0FFFF"); 
COLOR.LIGHTGOLDENRODYELLOW = new COLOR("#FAFAD2"); 
COLOR.LIGHTGREY = new COLOR("#D3D3D3"); 
COLOR.LIGHTGREEN = new COLOR("#90EE90"); 
COLOR.LIGHTPINK = new COLOR("#FFB6C1"); 
COLOR.LIGHTSALMON = new COLOR("#FFA07A"); 
COLOR.LIGHTSEAGREEN = new COLOR("#20B2AA"); 
COLOR.LIGHTSKYBLUE = new COLOR("#87CEFA"); 
COLOR.LIGHTSLATEBLUE = new COLOR("#8470FF"); 
COLOR.LIGHTSLATEGRAY = new COLOR("#778899"); 
COLOR.LIGHTSTEELBLUE = new COLOR("#B0C4DE"); 
COLOR.LIGHTYELLOW = new COLOR("#FFFFE0"); 
COLOR.LIME = new COLOR("#00FF00"); 
COLOR.LIMEGREEN = new COLOR("#32CD32"); 
COLOR.LINEN = new COLOR("#FAF0E6"); 
COLOR.MAGENTA = new COLOR("#FF00FF"); 
COLOR.MAROON = new COLOR("#800000"); 
COLOR.MEDIUMAQUAMARINE = new COLOR("#66CDAA"); 
COLOR.MEDIUMBLUE = new COLOR("#0000CD"); 
COLOR.MEDIUMORCHID = new COLOR("#BA55D3"); 
COLOR.MEDIUMPURPLE = new COLOR("#9370D8"); 
COLOR.MEDIUMSEAGREEN = new COLOR("#3CB371"); 
COLOR.MEDIUMSLATEBLUE = new COLOR("#7B68EE"); 
COLOR.MEDIUMSPRINGGREEN = new COLOR("#00FA9A"); 
COLOR.MEDIUMTURQUOISE = new COLOR("#48D1CC"); 
COLOR.MEDIUMVIOLETRED = new COLOR("#C71585"); 
COLOR.MIDNIGHTBLUE = new COLOR("#191970"); 
COLOR.MINTCREAM = new COLOR("#F5FFFA"); 
COLOR.MISTYROSE = new COLOR("#FFE4E1"); 
COLOR.MOCCASIN = new COLOR("#FFE4B5"); 
COLOR.NAVAJOWHITE = new COLOR("#FFDEAD"); 
COLOR.NAVY = new COLOR("#000080"); 
COLOR.OLDLACE = new COLOR("#FDF5E6"); 
COLOR.OLIVE = new COLOR("#808000"); 
COLOR.OLIVEDRAB = new COLOR("#6B8E23"); 
COLOR.ORANGE = new COLOR("#FFA500"); 
COLOR.ORANGERED = new COLOR("#FF4500"); 
COLOR.ORCHID = new COLOR("#DA70D6"); 
COLOR.PALEGOLDENROD = new COLOR("#EEE8AA"); 
COLOR.PALEGREEN = new COLOR("#98FB98"); 
COLOR.PALETURQUOISE = new COLOR("#AFEEEE"); 
COLOR.PALEVIOLETRED = new COLOR("#D87093"); 
COLOR.PAPAYAWHIP = new COLOR("#FFEFD5"); 
COLOR.PEACHPUFF = new COLOR("#FFDAB9"); 
COLOR.PERU = new COLOR("#CD853F"); 
COLOR.PINK = new COLOR("#FFC0CB"); 
COLOR.PLUM = new COLOR("#DDA0DD"); 
COLOR.POWDERBLUE = new COLOR("#B0E0E6"); 
COLOR.PURPLE = new COLOR("#800080"); 
COLOR.RED = new COLOR("#FF0000"); 
COLOR.ROSYBROWN = new COLOR("#BC8F8F"); 
COLOR.ROYALBLUE = new COLOR("#4169E1"); 
COLOR.SADDLEBROWN = new COLOR("#8B4513"); 
COLOR.SALMON = new COLOR("#FA8072"); 
COLOR.SANDYBROWN = new COLOR("#F4A460"); 
COLOR.SEAGREEN = new COLOR("#2E8B57"); 
COLOR.SEASHELL = new COLOR("#FFF5EE"); 
COLOR.SIENNA = new COLOR("#A0522D"); 
COLOR.SILVER = new COLOR("#C0C0C0"); 
COLOR.SKYBLUE = new COLOR("#87CEEB"); 
COLOR.SLATEBLUE = new COLOR("#6A5ACD"); 
COLOR.SLATEGRAY = new COLOR("#708090"); 
COLOR.SNOW = new COLOR("#FFFAFA"); 
COLOR.SPRINGGREEN = new COLOR("#00FF7F"); 
COLOR.STEELBLUE = new COLOR("#4682B4"); 
COLOR.TAN = new COLOR("#D2B48C"); 
COLOR.TEAL = new COLOR("#008080"); 
COLOR.THISTLE = new COLOR("#D8BFD8"); 
COLOR.TOMATO = new COLOR("#FF6347"); 
COLOR.TURQUOISE = new COLOR("#40E0D0"); 
COLOR.VIOLET = new COLOR("#EE82EE"); 
COLOR.VIOLETRED = new COLOR("#D02090"); 
COLOR.WHEAT = new COLOR("#F5DEB3"); 
COLOR.WHITE = new COLOR("#FFFFFF"); 
COLOR.WHITESMOKE = new COLOR("#F5F5F5"); 
COLOR.YELLOW = new COLOR("#FFFF00"); 
COLOR.YELLOWGREEN = new COLOR("#9ACD32");


/**
 * 调试等级
 */
const DEBUG_LEVE = function(e){
  this.leve = e;
  this.valueOf = function(){
    return this.leve
  }
  this.toString = function(){
    return this.leve
  }
}
DEBUG_LEVE.HIGH = new DEBUG_LEVE(100);
DEBUG_LEVE.MIDDLE = new DEBUG_LEVE(80);
DEBUG_LEVE.LOW = new DEBUG_LEVE(10);
DEBUG_LEVE.NONE = new DEBUG_LEVE(0);

module.exports.COLOR = COLOR;
module.exports.DEBUG_LEVE = DEBUG_LEVE;