on: push
name: actions.mini-program
jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: actions.mini-program
        uses: actions.mini-program@main
        with:
          project_type: miniProgram
          action_type: preview
          project_path: ./dist
          version: 1.0.0
          command_options:
            --enable-es6
            --project-ignores=['node_modules/**/*']
        env:
          MINI_APP_ID: ${{ secrets.MINI_APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.MINI_APP_PRIVATE_KEY }}